credentials:
  usernames:
    wesal:
      email: w.magdy2386@nu.edu.eg
      name: wesal
      password: "$2b$12$99vqkoiHATcGZyDwwxo7q.t.Dxft9YniGqUdjvauwrUGh3LSE90mu" 
      roles:
        - admin
    rana:
      email: r.mohsen2397@nu.edu.eg
      name: rana mohsen
      password: "$2b$12$A7FSsdqFBjMHlUaj6IpQw.7AqgZuRKv8DTKzZcPE6aDSjiFP/3VmK"
      roles:
        - supplier 
cookie:
  expiry_days: 30
  key: "ayhagamohema" 
  name: "auth_cookie"